version: '3'
services:
  rabbitmq_q:
    image: "rabbitmq:3.6-management"
    ports:
      - "8080:15672"
      - "5672:5672"
    expose:
      - 5672
    hostname: "rabbit"
    restart: always
networks:
    default:
        external:
            name: isolated_nw
