version: '3'

services:
  stackstorm:
    image: stackstorm/stackstorm:${ST2_IMAGE_TAG:-latest}
    env_file:
      - conf/stackstorm.env
      - conf/mongo.env
      - conf/rabbitmq.env
      - conf/postgres.env
      - conf/redis.env
    environment:
      - ST2_USER=st2admin
      - ST2_PASSWORD=st2admin
    ports:
      - "443:443"
    depends_on:
      - mongo
      - postgres
      - rabbitmq
      - redis
    networks:
      - isolated_nw
    volumes:
      - stackstorm-packs-volume:/opt/stackstorm/packs
      - stackstorm-virtualenvs-volume:/opt/stackstorm/virtualenvs
      - stackstorm-configs-volume:/opt/stackstorm/configs
      - stackstorm-log-volume:/var/log
      - ./packs.dev:/opt/stackstorm/packs.dev
      - ./runtime/entrypoint.d:/st2-docker/entrypoint.d
      - ./runtime/st2.d:/st2-docker/st2.d
      - ./conf/stackstorm.env:/st2-docker/env
    dns_search: .
    restart: always

### External Services

  mongo:
    image: mongo:3.4
    env_file:
      - conf/mongo.env
    networks:
      - isolated_nw
    volumes:
      - mongo-volume:/data/db
      - mongo-configdb-volume:/data/configdb
    dns_search: .
    restart: always
  rabbitmq:
    image: rabbitmq:3.6-management
    env_file:
      - conf/rabbitmq.env
    networks:
      - isolated_nw
    volumes:
      - rabbitmq-volume:/var/lib/rabbitmq
    dns_search: .
    restart: always
  postgres:
    image: postgres:9.6
    env_file:
      - conf/postgres.env
    networks:
      - isolated_nw
    volumes:
      - postgres-volume:/var/lib/postgresql/data
    dns_search: .
    restart: always
  redis:
    image: redis:4.0
    env_file:
      - conf/redis.env
    networks:
      - isolated_nw
    volumes:
      - redis-volume:/data
    dns_search: .
    command: [
      "bash", "-c",
      '
       docker-entrypoint.sh
       --requirepass "$$REDIS_PASSWORD"
      '
    ]
    restart: always

volumes:
  mongo-volume:
  mongo-configdb-volume:
  postgres-volume:
  rabbitmq-volume:
  redis-volume:
  stackstorm-packs-volume:
  stackstorm-virtualenvs-volume:
  stackstorm-configs-volume:
  stackstorm-log-volume:

networks:
    isolated_nw:
        external: true
